---
- name: 'Install github cli (Ubuntu)'
  block:
    - name: 'Add key'
      become: true
      apt_key:
        keyserver: 'keyserver.ubuntu.com'
        id: 'C99B11DEB97541F0'
    - name: 'Add repository'
      become: true
      command: 'sudo apt-add-repository https://cli.github.com/packages'
    - name: 'Install'
      become: true
      apt:
        name: 'gh'
        update_cache: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

