---
- name: 'Install essential packages (Ubuntu)'
  become: true
  apt:
    name: "{{ item }}"
    state: 'latest'
    update_cache: true
  loop:
    - 'build-essential'
    - 'curl'
    - 'direnv'
    - 'jq'
    - 'tmux'
    - 'xclip'
    - 'tig'
    - 'virtualbox'
    - 'vagrant'
    - 'silversearcher-ag'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install essential packages (Darwin)'
  homebrew:
    name: "{{ item }}"
    state: 'latest'
    update_homebrew: true
  loop:
    - 'curl'
    - 'direnv'
    - 'jq'
    - 'tmux'
    - 'tig'
    - 'virtualbox'
    - 'vagrant'
    - 'silversearcher-ag'
  when:
    - ansible_facts['distribution'] == 'Darwin'
 
