---
- name: 'Install essential packages (Ubuntu)'
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: 'latest'
    update_cache: true
  vars:
    apt_packages:
      - 'build-essential'
      - 'curl'
      - 'direnv'
      - 'jq'
      - 'tmux'
      - 'xclip'
      - 'tig'
      - 'virtualbox'
      - 'vagrant'
      - 'silversearcher-ag'
  tags:
    - 'update_deps'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install essential packages (Darwin)'
  homebrew:
    name: "{{ brew_packages }}"
    state: 'latest'
    update_homebrew: true
  vars:
    brew_packages:
      - 'curl'
      - 'direnv'
      - 'jq'
      - 'tmux'
      - 'tig'
      - 'ag'
  tags:
    - 'update_deps'
  when:
    - ansible_facts['os_family'] == 'Darwin'
- name: 'Install essential packages (Darwin cask)'
  homebrew_cask:
    name: "{{ item }}"
    state: 'latest'
  loop:
    - 'virtualbox'
    - 'vagrant'
  tags:
    - 'update_deps'
  when:
    - ansible_facts['os_family'] == 'Darwin'

