---
- name: 'Install neovim'
  block:
    - name: 'Install dependencies'
      become: true
      apt:
        name: "{{ item }}"
      loop:
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
    - name: 'Add neovim repo'
      become: true
      apt_repository:
        repo: 'ppa:neovim-ppa/stable'
    - name: 'Install neovim'
      become: true
      apt:
        name: neovim
    - name: 'Configure python related'
      shell: "{{ item }} install --upgrade neovim"
      loop:
        - "{{ home_dir }}/.pyenv/shims/pip3"
        - pip2
    - name: 'Update editor path'
      become: true
      shell: "update-alternatives --set {{ item }}"
      loop:
        - editor $(which nvim)
        - vi $(which nvim)
        - vim $(which nvim)
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

