---
- name: Setup go
  block:
    - name: Add go repository
      become: yes
      apt_repository:
        repo: ppa:longsleep/golang-backports
    - name: Install go
      become: yes
      apt:
        name: golang-go
        update_cache: yes
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: Install ghq
  shell: go get github.com/motemen/ghq

