---
- name: Setup xkeysnail
  block:
    - name: Install pip3
      become: yes
      apt:
        name: python3-pip
    - name: configure user
      block:
        - name: Add group
          become: yes
          group:
            name: uinput
            state: present
        - name: Add xkeysnail user
          become: yes
          user:
            name: xkeysnail
            create_home: no
            groups:
              - input
              - uinput
            shell: /usr/bin/nologin
        - name: Add uinput rules
          become: yes
          lineinfile:
            create: yes
            path: /etc/udev/rules.d/40-udev-xkeysnail.rules
            line: 'KERNEL=="uinput", GROUP="uinput"'
        - name: Add uinput conf
          become: yes
          lineinfile:
            create: yes
            path: /etc/modules-load.d/uinput.conf
            line: uinput
        - name: Add xkeysnail to sudoers
          become: yes
          lineinfile:
            path: /etc/sudoers
            line: 'bob ALL=(xkeysnail) NOPASSWD: /usr/local/bin/xkeysnail'
        - name: Launch xkeysnail on startup
          block:
            - name: Create a symlink to bin
              become: yes
              file:
                src: "{{ dotfiles_dir }}/tag-xkeysnail/launch_xkeysnail.sh"
                path: /usr/local/bin/launch_xkeysnail.sh
                state: link
            - name: Create a autostart directory
              file:
                path: "{{ home_dir }}/.config/autostart"
                state: directory
                recurse: yes
            - name: Create a symlink to autostart
              file:
                src: "{{ dotfiles_dir }}/tag-xkeysnail/xkeysnail.desktop"
                path: "{{ home_dir }}/.config/autostart/xkeysnail.desktop"
                state: link
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - wsl_enabled == false
