
---
- name: 'Install bat (Ubuntu)'
  become: true
  apt:
    deb: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb"
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
- name: 'Install bat (osx)'
  homebrew:
    name: 'bat'
    update_homebrew: true
    state: 'latest'
  when:
    - ansible_facts['os_family'] == 'Darwin'
