---
- name: 'Install docker (Ubuntu)'
  block:
    - name: 'Install dependencies'
      become: true
      apt:
        name: "{{ docker_dependencies }}"
        state: 'present'
        update_cache: true
      vars:
        docker_dependencies:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'gnupg-agent'
          - 'software-properties-common'
    - name: 'Add apt key'
      become: true
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: 'present'
    - name: 'Add apt repository'
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    - name: 'Install docker'
      become: true
      apt:
        name: "{{ docker_packages }}"
        state: 'present'
        update_cache: true
      vars:
        docker_packages:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'
    - name: 'Add docker group'
      become: true
      group:
        name: 'docker'
        state: 'present'
    - name: 'Add user to the docker group'
      become: true
      user:
        name: "{{ user_name }}"
        groups: 'docker'
        append: true
    - name: 'Install docker compose'
      become: true
      shell:
        cmd: "sudo curl -L \"https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
      vars:
        docker_compose_version: '1.25.4'
    - name: 'Add exectable permission for docker-compose'
      become: true
      file:
        path: '/usr/local/bin/docker-compose'
        mode: '0755'
  when:
    - ansible_facts['distribution'] == 'Ubuntu'

