---
- name: 'Install dependencies (Ubuntu)'
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

