---
- hosts: all
  tasks:
  - name: 'Setup git'
    include_role:
      name: 'git'
  - name: 'Setup dotfiles'
    include_role:
      name: 'dotfiles'
  - name: 'Setup xkeysnail'
    include_role:
      name: 'xkeysnail'

