---
- hosts: all
  tasks:
    - name: 'Setup git'
      include_role:
        name: 'git'
    - name: 'Setup dotfiles'
      include_role:
        name: 'dotfiles'
    - name: 'Setup xkeysnail'
      include_role:
        name: 'xkeysnail'
    - name: 'Install essential packages'
      include_role:
        name: 'essential_packages'
    - name: 'Install font'
      include_role:
        name: 'font'
    - name: 'Setup zsh'
      include_role:
        name: 'zsh'
    - name: 'Setup ruby'
      include_role:
        name: 'ruby'
    - name: 'Setup nodejs'
      include_role:
        name: 'nodejs'
    - name: 'Setup python'
      include_role:
        name: 'python'
    - name: 'Setup win32yank'
      include_role:
        name: 'win32yank'
    - name: 'Setup vim'
      include_role:
        name: 'vim'
    - name: 'Setup neovim'
      include_role:
        name: 'nvim'
    - name: 'Setup fzf'
      include_role:
        name: 'fzf'
    - name: 'Setup ghq'
      include_role:
        name: 'ghq'
    - name: 'Make symlink'
      include_role:
        name: 'symlink'
    - name: 'Setup fd'
      include_role:
        name: 'fd'
    - name: 'Setup rg'
      include_role:
        name: 'rg'
    - name: 'Setup bat'
      include_role:
        name: 'bat'
