---
- hosts: all
  tasks:
    - name: Install google chrome
      become: yes
      apt: 
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Setup git
      become: yes
      block:
        - name: Install git
          apt:
            name: git
            state: latest
            update_cache: yes
        - name: Install libgnome-keyring-dev
          apt:
            name: libgnome-keyring-dev
            state: latest
            update_cache: yes
        - name: build
          make:
            chdir: /usr/share/doc/git/contrib/credential/gnome-keyring
        - name: Make symlink
          file:
            src: /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
            dest: /usr/lib/git-core/git-credential-gnome-keyring
            owner: root
            group: root
            mode: '777'
            state: link
    - name: Setup dotfiles
      become: yes
      block:
        - name: Clone dotfiles
          git:
            repo: 'https://github.com/bob1983/dotfiles.git'
            dest: /home/bob/dotfiles
            update: no
        - name: Add thoughtbot keyring
          apt_key:
            url: 'https://apt.thoughtbot.com/thoughtbot.gpg.key'
            state: present
        - name: Add thoughtbot soucelist
          apt_repository:
            repo: deb https://apt.thoughtbot.com/debian/ stable main
            state: present
            filename: thoughtbot
        - name: Install rcm
          apt:
            name: rcm
            state: latest
            update_cache: yes
    - name: Install essential packages
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - build-essential
        - curl
        - direnv
        - jq
        - tmux
        - xclip
    - name: Configure zsh
      block:
        - name: Install zsh
          become: yes
          apt:
            name: zsh
            state: latest
            update_cache: yes
        - name: Use zsh as a login shell
          become: yes
          user:
            name: bob
            shell: /bin/zsh
 
