---
- hosts: all
  tasks:
    - name: Install google chrome
      become: yes
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: Setup git
      become: yes
      block:
        - name: Install git
          apt:
            name: git
            state: latest
            update_cache: yes
        - name: Install libgnome-keyring-dev
          apt:
            name: libgnome-keyring-dev
            state: latest
            update_cache: yes
        - name: build
          make:
            chdir: /usr/share/doc/git/contrib/credential/gnome-keyring
        - name: Make symlink
          file:
            src: /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring
            dest: /usr/lib/git-core/git-credential-gnome-keyring
            owner: root
            group: root
            mode: '777'
            state: link
    - name: Setup dotfiles
      become: yes
      block:
        - name: Clone dotfiles
          git:
            repo: 'https://github.com/bob1983/dotfiles.git'
            dest: /home/bob/dotfiles
            update: no
        - name: Add thoughtbot keyring
          apt_key:
            url: 'https://apt.thoughtbot.com/thoughtbot.gpg.key'
            state: present
        - name: Add thoughtbot soucelist
          apt_repository:
            repo: deb https://apt.thoughtbot.com/debian/ stable main
            state: present
            filename: thoughtbot
        - name: Install rcm
          apt:
            name: rcm
            state: latest
            update_cache: yes
    - name: Install essential packages
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - build-essential
        - curl
        - direnv
        - jq
        - tmux
        - xclip
    - name: Ensure /home/bob/.fonts dir exists
      file:
        path: /home/bob/.fonts
        state: directory
    - name: Install fonts
      get_url:
        url: "{{ item }}"
        dest: /home/bob/.fonts/
      loop:
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Italic.ttf'
        - 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold%20Italic.ttf'
      register: install_font_result
    - name: Update font cache
      shell: fc-cache -fv
      when: install_font_result.changed
    - name: Configure zsh
      block:
        - name: Install zsh
          become: yes
          apt:
            name: zsh
            state: latest
            update_cache: yes
        - name: Use zsh as a login shell
          become: yes
          user:
            name: bob
            shell: /bin/zsh
        - name: Check .zplug dir
          stat:
            path: /home/bob/.zplug
          register: zplug_dir
        - name: Install zplug
          shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
          when: not zplug_dir.stat.exists
    - name: Install vscode
      become: yes
      snap:
        name: code
        classic: yes
    - name: Install setting sync
      shell: code --install-extension Shan.code-settings-sync
    - name: Setup ruby
      block:
        - name: Install dependencies
          become: yes
          apt:
            name: "{{ item }}"
            state: latest
            update_cache: yes
          loop:
            - autoconf
            - bison
            - build-essential
            - libssl-dev
            - libyaml-dev
            - libreadline6-dev
            - zlib1g-dev
            - libncurses5-dev
            - libffi-dev
            - libgdbm5
            - libgdbm-dev
        - name: Install rbenv
          block:
            - name: Install rbenv
              git:
                repo: https://github.com/rbenv/rbenv.git
                dest: /home/bob/.rbenv
            - name: Install ruby-build
              git:
                repo: https://github.com/rbenv/ruby-build.git
                dest: /home/bob/.rbenv/plugins/ruby-build
        - name: Install ruby
          shell: /home/bob/.rbenv/bin/rbenv install --skip-existing 2.7.0
        - name: Set ruby 2.7.0 as global
          shell: /home/bob/.rbenv/bin/rbenv global 2.7.0
    - name: Install node
      block:
        - name: Install nodenv
          git:
            repo: https://github.com/nodenv/nodenv
            dest: /home/bob/.nodenv
        - name: Generate Makefile
          shell:
            chdir: /home/bob/.nodenv
            cmd: src/configure
        - name: Install nodenv bin
          make:
            chdir: /home/bob/.nodenv/src
        - name: Install node-build
          git:
            repo: https://github.com/nodenv/node-build
            dest: /home/bob/.nodenv/plugins/node-build
        - name: Install node
          shell: /home/bob/.nodenv/bin/nodenv install --skip-existing 12.14.0
        - name: Set node 12.14.0 as a global
          shell: /home/bob/.nodenv/bin/nodenv global 12.14.0
    - name: Install python
      block:
        - name: Install pyenv
          git:
            repo: https://github.com/pyenv/pyenv
            dest: /home/bob/.pyenv
        - name: Install python build dependencies
          become: yes
          apt:
            name: "{{ item }}"
          loop:
            - make
            - build-essential
            - libssl-dev
            - zlib1g-dev
            - libbz2-dev
            - libreadline-dev
            - libsqlite3-dev
            - wget
            - curl
            - llvm
            - libncurses5-dev
            - xz-utils
            - tk-dev
            - libxml2-dev
            - libxmlsec1-dev
            - libffi-dev
            - liblzma-dev
        - name: Install pyenv-virtualenv
          git:
            repo: https://github.com/pyenv/pyenv-virtualenv
            dest: /home/bob/.pyenv/plugins/pyenv-virtualenv
        - name: Install pyenv-doctor
          git:
            repo: https://github.com/pyenv/pyenv-doctor
            dest: /home/bob/.pyenv/plugins/pyenv-doctor
        - name: Install python
          shell: pyenv install --skip-existing 3.8.1
        - name: Set python 3.8.1 as a global
          shell: pyenv global 3.8.1
    - name: Install vim
      # Referenced by https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source
      block:
        - name: Update dependencies
          become: yes
          apt:
            name: "{{ item }}"
          loop:
            - libncurses5-dev
            - libgnome2-dev
            - libgnomeui-dev
            - libgtk2.0-dev
            - libatk1.0-dev
            - libbonoboui2-dev
            - libcairo2-dev
            - libx11-dev
            - libxpm-dev
            - libxt-dev
            - python-dev
            - python3-dev
            - ruby-dev
            - lua5.1
            - liblua5.1-dev
            - libperl-dev
            - git
        - name: Uninstall vim install by apt
          become: yes
          apt:
            name: "{{ item }}"
            state: absent
          loop:
            - vim
            - vim-runtime
            - gvim
        - name: Create base dir
          file:
            path: /home/bob/src/github.com/vim
            recurse: yes
            state: directory
        - name: Download vim repo
          git:
            repo: https://github.com/vim/vim
            dest: /home/bob/src/github.com/vim/vim
            depth: 1
        - name: Generate Makefile
          shell:
            chdir: /home/bob/src/github.com/vim/vim
            cmd: |
              ./configure \
                --with-features=huge \
                --enable-multibyte \
                --enable-rubyinterp=yes \
                --enable-python3interp=yes \
                --with-python3-config-dir=$(python3-config --configdir) \
                --enable-perlinterp=yes \
                --enable-luainterp=yes \
                --enable-gui=gtk2 \
                --enable-cscope \
                --prefix=/usr/local
        - name: Install vim
          become: yes
          make:
            chdir: /home/bob/src/github.com/vim/vim
            target: install
        - name: Update editor path
          become: yes
          shell: "update-alternatives {{ item }}"
          loop:
            - '--install /usr/bin/editor editor /usr/local/bin/vim 1'
            - '--set editor /usr/local/bin/vim'
            - '--install /usr/bin/vi vi /usr/local/bin/vim 1'
            - '--set vi /usr/local/bin/vim'
    - name: Install neovim
      block:
        - name: Install dependencies
          become: yes
          apt:
            name: "{{ item }}"
          loop:
            - python-dev
            - python-pip
            - python3-dev
            - python3-pip
        - name: Install neovim
          become: yes
          apt:
            name: neovim
        - name: python related
          become: yes
          shell: "{{ item }} install --upgrade neovim"
          loop:
            - pip2
            - pip3
        - name: Update editor path
          become: yes
          shell: "update-alternatives --set {{ item }}"
          loop:
            - editor $(which nvim)
            - vi $(which nvim)
            - vim $(which nvim)
      tags: test
